project_name: toy_ghost_proteome
output:
  directory: results

datasets:
  - name: toy_data
    type: standard_csv
    path: data/toy_proteins.csv
    level: protein
    group_col: PE_group

annotations:
  - name: toy_go
    type: long
    path: annotations/toy_terms.csv
    source: GO

analysis:
  summary: true
  comparisons:
    - dataset: toy_data
      group_col: PE_group
      group_a: PE1
      group_b: ghost
      features:
        - length
        - mw
        - pi
        - gravy
  enrichment:
    - dataset: toy_data
      group_col: PE_group
      query_group: ghost
      annotation: toy_go
      min_term_size: 2
